export const CART_ACTION_TYPES = {
  ADD_TO_CART: 'cart/ADD_TO_CART',
  REMOVE_FROM_CART: 'cart/REMOVE_FROM_CART',
  UPDATE_CART_ITEM: 'cart/UPDATE_CART_ITEM',
  CHANGE_ITEM_SIZE: 'cart/CHANGE_ITEM_SIZE',
  CLEAR_CART: 'cart/CLEAR_CART',
};
