// Mock data for admin dashboard demo

export const generateId = () => {
  return Math.random().toString(36).substr(2, 9);
};

export const formatDate = date => {
  return new Date(date).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
};

export const mockProducts = [
  {
    id: 'prod-1',
    name: 'Classic Denim Jeans',
    category: 'pants',
    price: 89.99,
    stock: 25,
    description: 'Comfortable classic fit denim jeans',
    images: ['https://placehold.co/300x400'],
    createdAt: '2024-01-15',
  },
  {
    id: 'prod-2',
    name: 'Summer Floral Dress',
    category: 'dresses',
    price: 129.99,
    stock: 12,
    description: 'Light and breezy summer dress with floral pattern',
    images: ['https://placehold.co/300x400'],
    createdAt: '2024-01-20',
  },
  {
    id: 'prod-3',
    name: 'Casual Cotton Shorts',
    category: 'shorts',
    price: 45.99,
    stock: 30,
    description: 'Comfortable cotton shorts for casual wear',
    images: ['https://placehold.co/300x400'],
    createdAt: '2024-01-25',
  },
  {
    id: 'prod-4',
    name: 'Elegant Black Skirt',
    category: 'skirts',
    price: 75.99,
    stock: 18,
    description: 'Sophisticated black skirt for formal occasions',
    images: ['https://placehold.co/300x400'],
    createdAt: '2024-02-01',
  },
  {
    id: 'prod-5',
    name: 'Trendy Graphic Tee',
    category: 'tops',
    price: 35.99,
    stock: 45,
    description: 'Comfortable graphic t-shirt with modern design',
    images: ['https://placehold.co/300x400'],
    createdAt: '2024-02-05',
  },
  {
    id: 'prod-6',
    name: 'Denim Dungarees',
    category: 'dungarees',
    price: 95.99,
    stock: 8,
    description: 'Stylish denim dungarees for a casual look',
    images: ['https://placehold.co/300x400'],
    createdAt: '2024-02-10',
  },
  {
    id: 'prod-7',
    name: 'High-Waist Trousers',
    category: 'pants',
    price: 79.99,
    stock: 22,
    description: 'Professional high-waist trousers',
    images: ['https://placehold.co/300x400'],
    createdAt: '2024-02-15',
  },
  {
    id: 'prod-8',
    name: 'Bohemian Maxi Dress',
    category: 'dresses',
    price: 149.99,
    stock: 6,
    description: 'Flowing bohemian style maxi dress',
    images: ['https://placehold.co/300x400'],
    createdAt: '2024-02-20',
  },
];

export const mockOrders = [
  {
    id: 'ord-1',
    orderNumber: 'MSQ-001',
    customerName: 'Sarah Johnson',
    customerEmail: 'sarah.j@email.com',
    status: 'accepted',
    totalPrice: 165.98,
    items: [
      { name: 'Classic Denim Jeans', quantity: 1, price: 89.99 },
      { name: 'Trendy Graphic Tee', quantity: 2, price: 35.99 },
    ],
    createdAt: '2024-02-25',
    shippingAddress: '123 Main St, Accra, Ghana',
  },
  {
    id: 'ord-2',
    orderNumber: 'MSQ-002',
    customerName: 'Michael Brown',
    customerEmail: 'mike.brown@email.com',
    status: 'in_transit',
    totalPrice: 129.99,
    items: [{ name: 'Summer Floral Dress', quantity: 1, price: 129.99 }],
    createdAt: '2024-02-24',
    shippingAddress: '456 Oak Ave, Kumasi, Ghana',
  },
  {
    id: 'ord-3',
    orderNumber: 'MSQ-003',
    customerName: 'Emily Davis',
    customerEmail: 'emily.davis@email.com',
    status: 'arrived',
    totalPrice: 121.98,
    items: [
      { name: 'Casual Cotton Shorts', quantity: 2, price: 45.99 },
      { name: 'Elegant Black Skirt', quantity: 1, price: 75.99 },
    ],
    createdAt: '2024-02-23',
    shippingAddress: '789 Pine St, Tamale, Ghana',
  },
  {
    id: 'ord-4',
    orderNumber: 'MSQ-004',
    customerName: 'David Wilson',
    customerEmail: 'david.wilson@email.com',
    status: 'cancelled',
    totalPrice: 95.99,
    items: [{ name: 'Denim Dungarees', quantity: 1, price: 95.99 }],
    createdAt: '2024-02-22',
    shippingAddress: '321 Elm St, Takoradi, Ghana',
  },
  {
    id: 'ord-5',
    orderNumber: 'MSQ-005',
    customerName: 'Lisa Anderson',
    customerEmail: 'lisa.anderson@email.com',
    status: 'processing',
    totalPrice: 229.98,
    items: [
      { name: 'High-Waist Trousers', quantity: 1, price: 79.99 },
      { name: 'Bohemian Maxi Dress', quantity: 1, price: 149.99 },
    ],
    createdAt: '2024-02-21',
    shippingAddress: '654 Maple Dr, Cape Coast, Ghana',
  },
  {
    id: 'ord-6',
    orderNumber: 'MSQ-006',
    customerName: 'James Taylor',
    customerEmail: 'james.taylor@email.com',
    status: 'accepted',
    totalPrice: 71.98,
    items: [{ name: 'Trendy Graphic Tee', quantity: 2, price: 35.99 }],
    createdAt: '2024-02-20',
    shippingAddress: '987 Cedar Ln, Sunyani, Ghana',
  },
];

export const mockUsers = [
  {
    id: 'user-1',
    name: 'Sarah Johnson',
    email: 'sarah.j@email.com',
    role: 'customer',
    joinedDate: '2024-01-15',
    lastLogin: '2024-02-25',
    totalOrders: 3,
    totalSpent: 425.95,
  },
  {
    id: 'user-2',
    name: 'Michael Brown',
    email: 'mike.brown@email.com',
    role: 'customer',
    joinedDate: '2024-01-20',
    lastLogin: '2024-02-24',
    totalOrders: 1,
    totalSpent: 129.99,
  },
  {
    id: 'user-3',
    name: 'Emily Davis',
    email: 'emily.davis@email.com',
    role: 'customer',
    joinedDate: '2024-01-25',
    lastLogin: '2024-02-23',
    totalOrders: 2,
    totalSpent: 217.97,
  },
  {
    id: 'user-4',
    name: 'David Wilson',
    email: 'david.wilson@email.com',
    role: 'customer',
    joinedDate: '2024-02-01',
    lastLogin: '2024-02-22',
    totalOrders: 1,
    totalSpent: 95.99,
  },
  {
    id: 'user-5',
    name: 'Lisa Anderson',
    email: 'lisa.anderson@email.com',
    role: 'customer',
    joinedDate: '2024-02-05',
    lastLogin: '2024-02-21',
    totalOrders: 1,
    totalSpent: 229.98,
  },
  {
    id: 'user-6',
    name: 'James Taylor',
    email: 'james.taylor@email.com',
    role: 'customer',
    joinedDate: '2024-02-10',
    lastLogin: '2024-02-20',
    totalOrders: 1,
    totalSpent: 71.98,
  },
  {
    id: 'admin-1',
    name: 'Admin User',
    email: 'admin@misqabbi.com',
    role: 'admin',
    joinedDate: '2024-01-01',
    lastLogin: '2024-02-25',
    totalOrders: 0,
    totalSpent: 0,
  },
];

export const orderStatuses = [
  { value: 'accepted', label: 'Accepted' },
  { value: 'processing', label: 'Processing' },
  { value: 'ready', label: 'Ready' },
  { value: 'enroute_pickup', label: 'En Route Pickup' },
  { value: 'picked_up', label: 'Picked Up' },
  { value: 'in_transit', label: 'In Transit' },
  { value: 'arrived', label: 'Arrived' },
];

export const userRoles = [
  { value: 'customer', label: 'Customer' },
  { value: 'admin', label: 'Admin' },
];
