export const FAVORITES_ACTION_TYPES = {
  ADD_FAVORITE: 'favorites/ADD_FAVORITE',
  REMOVE_FAVORITE: 'favorites/REMOVE_FAVORITE',
  TOGGLE_FAVORITE: 'favorites/TOGGLE_FAVORITE',
  CLEAR_FAVORITES: 'favorites/CLEAR_FAVORITES',
  SET_FAVORITES: 'favorites/SET_FAVORITES',
  SET_LOADING: 'favorites/SET_LOADING',
  SET_ERROR: 'favorites/SET_ERROR',
};
